language: python

python:
  - "2.7"

env:
  global:
    - secure: "QPh8mTbUD5fetzZHyhBOieFuv01VPFqjuzBuElFQvoMyBnV/svsDC0468fUcdaLEoXgpyUETr/QIMuWMfcLCFOoa7vVKMZmSM1kf0dh1NxBMSAZFkHFo1thxQV0yz+Nl9t4Ogm8iFZmyGxRXi1GubI8I+oRfe9vyuBuCySHW36M="

install:
  - pip install -r requirements.txt -q
  - npm install less

before_script:
  - git config --global user.email "go.anoa@gmail.com"
  - git config --global user.name "Travis"

script:
  - cd output
  - git checkout master
  - git pull
  - cd ..
  - cp CNAME output
  - pelican
  - make publish
  - cd output
  - git add -f .
  - git commit -a -m "add new site content"
  - test $? -eq "0" && git push https://${GH_TOKEN}@github.com/an0a/ab0a.github.io.git master --quiet
  
